apiVersion: v1
kind: Pod
metadata:
  name: liveness-pod
  labels:
    app: probe-test-pod
spec:
  containers:
    - name: k8s-probe-test
      image: dev.pcr.kr/1004359/k8s-probe-test:1.0
      ports:
      - containerPort: 2255
