apiVersion: v1
kind: Pod
metadata:
  name: startup-pod
  labels:
    app: probe-test-pod
spec:
  containers:
    - name: k8s-probe-test
      image: dev.pcr.kr/1004359/k8s-probe-test:1.0
      ports:
      - containerPort: 2255
      startupProbe:
        httpGet:
          path: /probe/startup
          port: 8080
        failureThreshold: 30
        periodSeconds: 2
      livenessProbe:
        httpGet:
          path: /probe/liveness
          port: 8080
        initialDelaySeconds: 10
        periodSeconds: 5
