apiVersion: v1
kind: Service
metadata:
  name: probe-test-service
spec:
  selector:
    app: probe-test-pod
  ports:
    - protocol: TCP
      port: 2255
      targetPort: 8080
      nodePort: 32255
  type: NodePort